spring.application.name=inventario-empresa

# Conexao com o PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5434/inventariodb
spring.datasource.username=admin
spring.datasource.password=123

# Desligando a criacao automatica do schema pelo Hibernate (Flyway gerencia as migracoes)
spring.jpa.hibernate.ddl-auto=validate

# OpenAPI / Swagger UI
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

